@startuml application
scale 2
left to right direction
skinparam packageStyle rect

:user:
:host:
:system:

rectangle "application" {  



    host -|> user
    
    (user) -- (signup)      
    (user) -- (view apartments)
    host -- (login host)

    signup .>  (login): <<include>>

    login <.. (make reservation): <<extends>>
    (make reservation) ..> (make payment): <<include>>
    (make reservation) ..> (send/get email): <<include>>
    system -- (send/get email)
    login <.. (view credentials): <<extends>>
    login <.. (view profile): <<extends>>
    login <.. (view reservations): <<extends>>
    (login) <.. (logout): <<extends>>

    login -|> (login host)
    (login host) <.. (view earnings): <<extends>>
    (login host) <.. (create apartment): <<extends>>
    (login host) <.. (view customer reservation ): <<extends>>

    'forse questi non ci vanno'
    (view apartments) ..> (use searchbar): <<include>>
    (view apartments) <.. (make review): <<extends>>
    (view apartments) ..> (use filters): <<include>>
    
    
}

@enduml
