@startuml useraccess
scale 2
left to right direction
skinparam packageStyle rect

:user:
:host:

rectangle "application" {



    host -|> user
    
    (user) -- (signup)      
    (user) -- (logout)  
    (user) -- (view apartments)
    host -- (login host)

    signup .>  (login): <<include>>

    login <.. (make reservation): <<extends>>
    (make reservation) ..> (make payment): <<include>>
    login <.. (view credentials): <<extends>>
    login <.. (view profile): <<extends>>
    login <.. (view reservations): <<extends>>

    login -|> (login host)
    (login host) ..> (view earnings): <<include>>
    (login host) ..> (create apartment): <<include>>

    (view apartments) ..> (use searchbar): <<include>>
    (view apartments) ..> (use filters): <<include>>

    
    
}

@enduml