@startuml classdiagram
left to right direction

class Apartment {
  +ObjectId _id
  +User host
  +String name
  +String description
  +Number price
  +Number bathrooms
  +Number beds
  +Number guests_max
  +String type_accomodation
  +Array services
  +Array photo_paths
  .. address ..
  +String country
  +String postal_code
  +String street
  +String street_number
  +String province
  +String town
}

@enduml