@startuml classdiagram
left to right direction

class Apartment {
  +ObjectId _id
  +ObjectId host
  +String name
  +String description
  +Number price
  +Number beds
  +String type_accomodation
  +Array services
  +Array photo_paths
  +Address address
}

class Address {
    +String country
    +String city
    +String province
    +String street
    +String number
    +String zip
}

Address *-- Apartment

@enduml