@startuml classdiagram
left to right direction

class Reservation {
  +ObjectId apartment
  +ObjectId customer
  +ObjectId host
  +Date checkin
  +Date checkout
  +String payment_citytax
  +String payment_method
  +Array guests
  +String email
  +String telephoneNumber
  +Address address
  +Date birthdate
  --
  +User()
  +User(String username, String password)
}


@enduml