@startuml show-reservations

actor User
participant "Index" as Index
participant "Reservation\nController" as ReservationController    
database Database

activate User

        
    User -> Index: GET: /reservations
    activate Index
      Index -> ReservationController: renderReservations()
    activate ReservationController
    ReservationController -> ReservationController: render(index)
    Index <- ReservationController: display reservations

@enduml