@startuml logout

actor User
participant "Index" as Index
participant "User\nController" as UserController

activate User
    User -> Index: GET /users/logout
    activate Index
    Index -> UserController: \t logout()

        activate UserController
            UserController -> UserController: process the request
            Index <-- UserController: display message


        deactivate UserController
deactivate User

@enduml