@startuml signup

actor User
participant "Current\nPage" as CurrentPage
participant "Signup\nScreen" as SignupScreen
participant "User\nController" as UserController
database Database

activate User
    activate CurrentPage
        User -> CurrentPage: open the app
        CurrentPage -> SignupScreen: click on register button
    deactivate CurrentPage

    activate SignupScreen
        SignupScreen -> UserController: insert credentials
        activate UserController
        UserController -> UserController: the controller\nprocess the request
        SignupScreen x-- UserController: display error message
        UserController -> Database: the controller inserts\n  user on DB
        deactivate UserController

        activate Database
        SignupScreen x-- Database : \n     show error
    deactivate SignupScreen
    activate CurrentPage
    deactivate CurrentPage
    CurrentPage <-- Database: successful registration
    User <-- CurrentPage: Close app
    deactivate Database
deactivate User

@enduml