@startuml signup

actor User
participant "Index" as Index
participant "Signup\nScreen" as SignupScreen
participant "User\nController" as UserController
database Database

activate User

        
    User -> Index: click on signup button
    activate Index
    Index --> SignupScreen: submit credentials
    activate SignupScreen
        SignupScreen -> UserController: verify credentials
        activate UserController
        UserController -> UserController: the controller\nprocess the request
        alt no errors
        UserController -> Database: the controller inserts\n  user on DB
        activate Database
        alt successfully inserted
        UserController <-- Database: return success
        SignupScreen <-- UserController: display success message
    deactivate SignupScreen
    Index <-- Database: successful registration
        else not inserted
        activate SignupScreen
        UserController x-- Database: return insert error
        SignupScreen x-- UserController: display error message
        deactivate UserController
        
        deactivate SignupScreen
        end
        else credentials error
        SignupScreen x-- UserController: display credentials errors
        activate SignupScreen

        activate UserController
        SignupScreen x-- Database : \n     show error
        deactivate UserController
        deactivate SignupScreen
  

        end
    deactivate Database
deactivate User

@enduml