@startuml signin

actor User
participant "Index" as Index
participant "Signin\nModal" as SigninModal
participant "User\nController" as UserController
database Database

activate User
        User -> Index: open signin-modal
    activate Index
        Index -> SigninModal: submit POST /users/signin
    
    

    activate SigninModal
        SigninModal -> UserController: async signin()
        activate UserController
        UserController -> Database: User.findOne()
        activate Database
        alt user found
        UserController <- Database : \n    return true
        SigninModal <- UserController: user found
        
        SigninModal <- SigninModal: display success message
        Index <- SigninModal: go to #
        
        else mismatch or not found
        UserController x- Database : \n    return false
        deactivate Database
        SigninModal x- UserController: return error type
        SigninModal <- SigninModal: display error message
        deactivate UserController
        end

    
deactivate User

@enduml