@startuml signin

actor User
participant "Index" as Index
participant "Signin\nModal" as SigninModal
participant "User\nController" as UserController
database Database

activate User
        User -> Index: click on signin button
    activate Index
        Index -> SigninModal: send credentials (submit) 
    
    

    activate SigninModal
        SigninModal -> UserController: verify credentials
        activate UserController
        UserController -> Database: search for user
        activate Database
        alt user found
        UserController <-- Database : \n    return user
        SigninModal <-- UserController: task completed
        
        Index <-- SigninModal: return to current page
        
        else user not found
        UserController x-- Database : \n    return not found error
        deactivate Database
        SigninModal x-- UserController: display error message
        deactivate UserController
        deactivate SigninModal
        end

    
deactivate User

@enduml