@startuml signin

actor User
participant "Current\nPage" as CurrentPage
participant "Signin\nModal" as SigninModal
participant "User\nController" as UserController
database Database

activate User
    activate CurrentPage
        User -> CurrentPage: open the app
        CurrentPage -> SigninModal: (  if (session.user)  )\n click on signin button
    

    activate SigninModal
        SigninModal -> UserController: insert credentials
        activate UserController
        UserController -> Database: the controller\nsearch if user exist
        activate Database
        UserController <-- Database : \n    user found
        SigninModal <-- UserController: task completed
        CurrentPage <-- SigninModal: return to current page
        UserController x-- Database : \n    user not found
        SigninModal x-- UserController: display error message
        deactivate Database
        deactivate UserController

    deactivate SigninModal
    
    User <-- CurrentPage: Close app
    deactivate CurrentPage
deactivate User

@enduml